<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>ScreenDemoRecorder</AssemblyName>
    <RootNamespace>ScreenDemoRecorder</RootNamespace>
    <Version>1.0.2</Version>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Vortice.Direct3D11" Version="3.8.3" />
    <PackageReference Include="Vortice.Direct2D1" Version="3.8.3" />
    <PackageReference Include="Vortice.MediaFoundation" Version="3.8.3" />
    <ProjectReference Include="..\ScreenDemoRecorder.Core\ScreenDemoRecorder.Core.csproj" />
  </ItemGroup>
</Project>
